# pre-installation
- name: Import repository
  shell: |
    curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | apt-key add -
    echo "deb https://apache.bintray.com/couchdb-deb bionic main" | tee -a /etc/apt/sources.list
    
# install couchdb
- name: Install CouchDB
  shell: |
    echo "couchdb couchdb/mode select none" | debconf-set-selections
    apt update
    DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes couchdb


    
