# import repo
- name: Add CouchDB repositories when os=cenos
  shell: |
    yum install -y yum-utils
    yum-config-manager --add-repo https://couchdb.apache.org/repo/couchdb.repo
    yum install -y couchdb
  when: ansible_distribution == "CentOS"

- name: Add CouchDB repositories when os=other
  shell: |
    sudo apt update && sudo apt install -y curl apt-transport-https gnupg
    curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1
    source /etc/os-release
    echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null
    apt update
    apt install -y couchdb
  when: ansible_distribution != "CentOS"

# install couchdb
- name: Install CouchDB
  yum:
    name: couchdb
    update_cache: yes
  
